In [1]:
import numpy as np

In [2]:
# 数组的构造
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# 等差数列 
np.linspace(1,5,11) # np.linspace(起始值，终止值（包含），样本个数)

np.arange(1,5,2) # np.arange(起始值，终止值（不包含），步长)

array([1, 3])

In [4]:
#2. zeros 零矩阵
np.zeros((2,3)) # np.zeros((m,n)) 创建m行 n列 0 矩阵

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# 单位阵
np.eye(3)  #np.eye((m)) 创建m行 单位阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#单位阵
np.eye(4,k=1) # 对角线偏移k个单位

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [7]:
# full
np.full((4,2),5) #np.full((m,n),k) 创建m行 n列 填充k值的矩阵 k -> str / list 

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [8]:
# np.random 随机矩阵
np.random.rand(2)   # np.random.rand(k) 生成服从0-1 均匀分布的k个随机数

array([0.89649833, 0.62761503])

In [9]:
# np.random.randn 
np.random.randn(3) # 标准正态分布

array([-1.12838262, -0.75676742,  0.2794843 ])

In [10]:
#np.random.randint 指定生成随机整数的最大值最小值和维度大小
np.random.randint( 5,12,(3,3))

array([[ 7,  9,  6],
       [ 8,  9, 10],
       [ 6,  9,  8]])

In [11]:
#np.random.choice 从指定列表中抽样,默认又放回抽样
choice_list = [1,2,3,4,6,5]
np.random.choice(choice_list,3,replace=False)

array([4, 3, 5])

In [12]:
# 随机数种子
np.random.seed(1) # 可以固定随机数的输出结果。
np.random.rand()

0.417022004702574

In [13]:
# np 数组的变形与合并
# 转置
np.zeros((3,2)).T

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 合并r_(上下合并) c_左右合并
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
# 维度表换 reshape 将原有数组按新的维度重新排列，C模式按行读取，f模式按列的顺序进行填充读取
target = np.arange(8).reshape(2,4,order= 'C')
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
target = np.arange(8).reshape(2,4,order= 'F')
target

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [18]:
# 数组的切片和素银
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
target[0:2,[0,2]]

array([[0, 2],
       [3, 5]])

In [20]:
# 利用bool值
target[np.ix_([True,True])]

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# 常用函数
a = np.array([1,0,4,5,0,8,10]) # 满足指定条件与不满足指定条件填充值
np.where(a> 4,a,5 )  #类方法

array([ 5,  5,  5,  5,  5,  8, 10])

In [22]:
# nonzero ,argmax ,argmin  返回索引 类方法
np.nonzero(a)
np.argmax(a)

6

In [23]:
# any 当序列至少存在一个True 或者非零元素时返回True, all全为True
a = np.array([0,1])
a.any(),a.all()

(True, False)

In [24]:
# cumpor cumsum .diff
a = np.array([1,2,3])
np.cumprod(a),np.cumsum(a),np.diff(a)

(array([1, 2, 6]), array([1, 3, 6]), array([1, 1]))

In [25]:
# 常用统计函数
# max,min,mean,median,std,var,sum,quantile. 其中quantile 为全局函数 不能通过array.quantile调用
a = np.array([1,2,3,4])
a.max(),a.min(),a.std(),a.var(),np.quantile(a,0.1)

(4, 1, 1.118033988749895, 1.25, 1.3)

In [26]:
# cov 计算协方差,corrcoef计算相关系数
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
np.cov(a,b),np.corrcoef(a,b)

(array([[1.66666667, 1.66666667],
        [1.66666667, 1.66666667]]),
 array([[1., 1.],
        [1., 1.]]))